### ISSUE TITLE
Not working with FIJI on MacOS

### ISSUE THREAD

**Issue by conlank** [pmascalchi/ImageJ_Export-LIF-as-IndividualImages#1]
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at loci.plugins.macro.MacroFunctions.handleExtension(MacroFunctions.java:82)
	at ij.macro.ExtensionDescriptor.dispatch(ExtensionDescriptor.java:288)
	at ij.macro.Functions.doExt(Functions.java:4697)
	at ij.macro.Functions.getStringFunction(Functions.java:275)
	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1360)
	at ij.macro.Interpreter.getString(Interpreter.java:1338)
	at ij.macro.Interpreter.doStatement(Interpreter.java:303)
	at ij.macro.Interpreter.doBlock(Interpreter.java:635)
	at ij.macro.Interpreter.doStatement(Interpreter.java:294)
	at ij.macro.Interpreter.doFor(Interpreter.java:557)
	at ij.macro.Interpreter.doStatement(Interpreter.java:276)
	at ij.macro.Interpreter.doStatements(Interpreter.java:235)
	at ij.macro.Interpreter.runMacro(Interpreter.java:156)
	at ij.macro.MacroRunner.run(MacroRunner.java:152)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /Users/user/Desktop/folder/08-15-2018 CNP LysM SynI tdt\syn1 tdt neun-green.lif (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:123)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:139)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:148)
	at loci.common.Location.getHandle(Location.java:324)
	at loci.common.Location.getHandle(Location.java:294)
	at loci.common.Location.getHandle(Location.java:284)
	at loci.common.Location.getHandle(Location.java:274)
	at loci.common.Location.checkValidId(Location.java:349)
	at loci.formats.ImageReader.getReader(ImageReader.java:177)
	at loci.formats.ImageReader.setId(ImageReader.java:839)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:291)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.plugins.macro.LociFunctions.setId(LociFunctions.java:427)

```

I think the issue is the "\" direction. I will try editing the macro and reporting back.

**Comment by pmascalchi** [comment]
Thanks for the feedback, that was an old piece of code...
I changed two lines where there were obvious issues and named the new version Export-LIF-as-Individual-Images_1.3.
Let me know if problem is solved...
